version: "3"
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sunrise
      MYSQL_USER: sunrise_user
      MYSQL_PASSWORD: VMnj5L2v8N5bzgnQ
